### ISSUE TITLE
Lint errors on missing dependencies in useEffect hooks

### ISSUE THREAD

**Issue by verheyenkoen** [DJanoskova/React-validator-demo#4]
I'm trying to include this code in my project but I get these lint errors in my console (everything seems to work fine though):

```
  Line 22:  React Hook useEffect has missing dependencies: 'handleValidation' and 'value'. Either include them or remove the dependency array  react-hooks/exhaustive-deps
  Line 33:  React Hook useEffect has a missing dependency: 'value'. Either include it or remove the dependency array                           react-hooks/exhaustive-deps
  Line 41:  React Hook useEffect has a missing dependency: 'handleValidation'. Either include it or remove the dependency array                react-hooks/exhaustive-deps
```

Do these dependencies need to be optimized or should I add linting hints to ignore these hook definitions?

**Comment by DJanoskova** [comment]
@verheyenkoen I'm very sorry, I didn't notice this new issue.
Yeah you're right, I've worked on this and I'll be uploading a new version very soon 😊

**Comment by DJanoskova** [comment]
`validator.js` is updated, `validatorWithTooltip.js` not just yet, but it's almost the same code. Feel free to check it out if you're interested!

**Comment by verheyenkoen** [comment]
Is there any change in how to use it because I'm getting errors now?

> Warning: Received `false` for a non-boolean attribute `error`.
> 
> If you want to write it to the DOM, pass a string instead: error="false" or error={value.toString()}.
> 
> If you used to conditionally omit it with error={condition && value}, pass error={condition ? value : undefined} instead.

**Comment by DJanoskova** [comment]
@verheyenkoen There shouldn't be. Thanks for notifying me, I'll have a look at it

**Comment by DJanoskova** [comment]
@verheyenkoen Hi, I tried to fix everything. The changes are pushed, I hope it works well!

**Comment by verheyenkoen** [comment]
Thanks for the update. Not sure what I'm doing wrong but I get this error now:

> TypeError: Cannot create property 'protocols' on boolean 'true'

**Comment by DJanoskova** [comment]
@verheyenkoen Could you maybe share the source code, please? I can't seem to find out how to reproduce this, I'm sorry.

**Comment by verheyenkoen** [comment]
Apparently the error comes from validator (I'm using the `isURL` method) but not sure if the problem is there or in your code.

Anyway, I made a reproducible repo: https://github.com/verheyenkoen/react-validator-demo-bug. The error occurs on the first keystroke in the input field.

**Comment by DJanoskova** [comment]
@verheyenkoen Thanks a lot! I was able to fix it.

I updated this code in `validator.js`:

```
fields.forEach(field => {
    const { rule, options = null } = field

    switch (rule.trim()) {
      case 'isRequired':
        if (!value) isValid = false
        break
      default:
        if (isValid) {
          if (options !== null) {
            let result
            switch (options) {
              case true:
                result = validator[rule](value)
                break
              case false:
                result = !validator[rule](value)
                break
              default:
                result = validator[rule](value, options)
            }
            isValid = result
          } else isValid = validator[rule](value)
          break
        }
    }
  })
```

Please let me know if it works? I'll update the source code soon.

Best regards,
Dana

**Comment by verheyenkoen** [comment]
That seems to be doing it for me, thanks!
